### ISSUE TITLE
Strange behaviors of cd-fill-parent and font-size

### ISSUE THREAD

**Issue by aure** [yamartino/CSSDevices#4]
First, cd-fill-parent only fills properly if you also include a style with font-size:100% and second the size seems to be inversely proportional to font-size as is shown by the following: (Click the edit pencil to see the html)

<div style="width:400px; background: green">
    <div class="cd-iphone-5c cd-blue cd-fill-parent cd-silver cd-landscape-left" style="margin-left: 1em; margin-bottom: 2em; font-size: 100%">
      <div class="cd-body">
        <div class="cd-sound"></div>
        <div class="cd-sleep"></div>
        <div class="cd-camera"></div>
        <div class="cd-ear"></div>
        <div class="cd-home"></div>
        <div class="cd-screen">
          <video controls class="cd-fill">
            <source src="https://dl.dropboxusercontent.com/u/31568349/movies/Keyboard.m4v" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
      </div>
    </div>
</div>

<div style="width:400px; background: green">
    <div class="cd-iphone-5c cd-blue cd-fill-parent cd-silver cd-landscape-left" style="margin-left: 1em; margin-bottom: 2em;">
      <div class="cd-body">
        <div class="cd-sound"></div>
        <div class="cd-sleep"></div>
        <div class="cd-camera"></div>
        <div class="cd-ear"></div>
        <div class="cd-home"></div>
        <div class="cd-screen">
          <video controls class="cd-fill">
            <source src="https://dl.dropboxusercontent.com/u/31568349/movies/Keyboard.m4v" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
      </div>
    </div>
</div>

<div style="width:400px; background: green">
    <div class="cd-iphone-5c cd-blue cd-fill-parent cd-silver cd-landscape-left" style="margin-left: 1em; margin-bottom: 2em; font-size: 130%">
      <div class="cd-body">
        <div class="cd-sound"></div>
        <div class="cd-sleep"></div>
        <div class="cd-camera"></div>
        <div class="cd-ear"></div>
        <div class="cd-home"></div>
        <div class="cd-screen">
          <video controls class="cd-fill">
            <source src="https://dl.dropboxusercontent.com/u/31568349/movies/Keyboard.m4v" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
      </div>
    </div>
</div>

<div style="width:400px; background: green">
    <div class="cd-iphone-5c cd-blue cd-fill-parent cd-silver cd-landscape-left" style="margin-left: 1em; margin-bottom: 2em; font-size: 60%">
      <div class="cd-body">
        <div class="cd-sound"></div>
        <div class="cd-sleep"></div>
        <div class="cd-camera"></div>
        <div class="cd-ear"></div>
        <div class="cd-home"></div>
        <div class="cd-screen">
          <video controls class="cd-fill">
            <source src="https://dl.dropboxusercontent.com/u/31568349/movies/Keyboard.m4v" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
      </div>
    </div>
</div>

which produces:

![screen shot 2015-01-23 at 3 18 00 am](https://cloud.githubusercontent.com/assets/13122/5873767/c03b72dc-a2ae-11e4-972f-ed9d85e3ac63.png)

**Comment by Yamartino** [comment]
First of all, I am not so sure you are using the most recent version of CSSDevices which prevents the device flash in a different size before the JS kicks in when the page loads.

I am working on a fix for having to set 100% font-size; however I am not sure that the setting of a different font-size with the cd-fill-parent behavior will change. Is there something you need that for or were you just pointing out that it was a strange behavior? I'm gonna try to figure out how much control I have over that issue, looking into it further.
